### ISSUE TITLE
task always need a build parameters

### ISSUE THREAD

**Issue by daanvanham** [konfirm/devour-gulp#2]
I've got a few tasks in my gulpfile which don't need this parameter, but without them the task can't be added.

e.g.:

```
gulp.task('clean', function() {
    del(['./dist/script/*.js', '!./dist/script/main.js']);
});
```

But such a task can't be added to `Devour` and running it without adding it in the gulpfile obviously doesn't work.

**Comment by rspieker** [comment]
Added the option to leave out the `build` (and therefor `watch`) to v1.3.1, this enables a no-op mode, which does not receive a stream (`null` instead).

You still need a task-file, but you can now activate the task like:

``` js
new Devour()
    .task('noop')
;
```

The only way to actually run this task is to run it manually using `devour noop`

**Comment by daanvanham** [comment]
Works like a charm, thanks!
